### ISSUE TITLE
Find out how colors are assigned in calendar and try to add metadata to entries so colors are predictable

### ISSUE THREAD

**Issue by bmamlin** [maurya/openmrs-module-patientportaltoolkit#111]
The calendar widget assigns colors to entries, but we do not yet know how colors are chosen. While we do not need to control which colors are used, we'd like to be able to ensure that similar entries get the same color.

**Comment by maurya** [comment]
Please check the below snapshots for different years and different dates having predictable colors
<img width="1072" alt="screen shot 2017-02-13 at 10 41 57 am" src="https://cloud.githubusercontent.com/assets/1560244/22890057/26dbc8a4-f1d9-11e6-991c-e8bafdfb2297.png">
<img width="1233" alt="screen shot 2017-02-13 at 10 41 51 am" src="https://cloud.githubusercontent.com/assets/1560244/22890060/26e7a016-f1d9-11e6-9bbe-f29fd7b15e01.png">
<img width="1182" alt="screen shot 2017-02-13 at 10 41 43 am" src="https://cloud.githubusercontent.com/assets/1560244/22890058/26dc680e-f1d9-11e6-8d40-f2d99c3d61c8.png">
<img width="1074" alt="screen shot 2017-02-13 at 10 41 31 am" src="https://cloud.githubusercontent.com/assets/1560244/22890059/26e5979e-f1d9-11e6-834b-c2ce3b2a7be6.png">

**Comment by maurya** [comment]
Fix colors to be only in darker shades for legibility

**Comment by maurya** [comment]
This should reflect in preventive care
