### ISSUE TITLE
Instead of showing "undefined" location info in calendar, show either "Completed" or "Due next" as subtitle

### ISSUE THREAD

**Issue by bmamlin** [maurya/openmrs-module-patientportaltoolkit#112]

**Comment by maurya** [comment]
https://github.com/maurya/openmrs-module-patientportaltoolkit/commit/8d97fa753858dbbd7d275a5cabd7b964b13b53e2

<img width="1348" alt="screen shot 2017-03-17 at 4 15 58 pm" src="https://cloud.githubusercontent.com/assets/1560244/24061370/9778a4c0-0b2d-11e7-905c-03349913a565.png">
<img width="1361" alt="screen shot 2017-03-17 at 4 16 07 pm" src="https://cloud.githubusercontent.com/assets/1560244/24061371/97828cec-0b2d-11e7-9648-7f903655a8d7.png">
