### ISSUE TITLE
Doctor and patients should be able to manage (add/edit/delete) follow up events in calendar

### ISSUE THREAD

**Issue by bmamlin** [maurya/openmrs-module-patientportaltoolkit#114]

**Comment by uladkasach** [comment]
Are there any things besides `appointment date` that the user should be able to edit for an event?

**Comment by maurya** [comment]
The user needs to only set the completed date (appointment date should either be autogenerated or added by the doctor)

**Comment by uladkasach** [comment]
@maurya What about for the `edit` part of event management?

**Comment by maurya** [comment]
The patient should be able to edit the completed date. Similarly, the doctor should be able to edit the appointment date

**Comment by maurya** [comment]
<img width="1357" alt="screen shot 2017-04-20 at 11 20 09 am" src="https://cloud.githubusercontent.com/assets/1560244/25238421/605b45e4-25bb-11e7-9af9-9ed355d5c03a.png">
