### ISSUE TITLE
Project-specific login page

### ISSUE THREAD

**Issue by bmamlin** [maurya/openmrs-module-patientportaltoolkit#115]
The "landing page" for users should be branded for the project. For example, users should not need to pick a location (as is required for the generic reference application screen). A first pass can be recreating the login page from the legacy system.

Once logged in, users should go directly to their home page for the personal cancer toolkit (not the OpenMRS home page).

**Comment by uladkasach** [comment]
![screenshot_2017-05-10_13-44-20](https://cloud.githubusercontent.com/assets/10381896/25912876/c9857f6e-3586-11e7-9625-2d4c534e6c60.png)

**Comment by uladkasach** [comment]
This was implemented with pull request #216 

The background image should be updated to use one that does not have watermarks.

The implementation remaps the `/login.htm` path from thel `module-referenceapplication` login page to our custom login page, which then implements a very reduced version of the original `module-referenceapplication` login logic.

**Comment by maurya** [comment]
<img width="1464" alt="screen shot 2017-05-11 at 3 05 41 pm" src="https://cloud.githubusercontent.com/assets/1560244/25967202/55df7922-365b-11e7-9900-81d13f12b692.png">
