### ISSUE TITLE
Confirm a patient not yet enrolled in CancerBuddies can see patients in the program

### ISSUE THREAD

**Issue by bmamlin** [maurya/openmrs-module-patientportaltoolkit#117]

**Comment by maurya** [comment]
<img width="1337" alt="screen shot 2017-02-15 at 12 04 11 pm" src="https://cloud.githubusercontent.com/assets/1560244/22986574/0bbb0902-f37a-11e6-946d-6fa2b69ba194.png">
<img width="1327" alt="screen shot 2017-02-15 at 12 03 13 pm" src="https://cloud.githubusercontent.com/assets/1560244/22986601/18f8354a-f37a-11e6-833d-3aa780afb875.png">

**Comment by maurya** [comment]
can be tested out at https://personalcancertoolkit.org

with username:password - demo5:Admin123
