### ISSUE TITLE
Ensure there are demo patients who have a a mix of relationships through connection and CancerBuddies

### ISSUE THREAD

**Issue by bmamlin** [maurya/openmrs-module-patientportaltoolkit#118]
We want to make sure there are examples of patients in the demo dataset who have relationship through Connections, through CancerBuddies, and through a mix of both.

**Comment by maurya** [comment]
<img width="1328" alt="screen shot 2017-02-15 at 12 03 30 pm" src="https://cloud.githubusercontent.com/assets/1560244/22986707/64542508-f37a-11e6-946f-c7f54dc96342.png">
<img width="1162" alt="screen shot 2017-02-15 at 12 01 17 pm" src="https://cloud.githubusercontent.com/assets/1560244/22986722/6f612edc-f37a-11e6-88d5-687de5f1c003.png">

**Comment by maurya** [comment]
can be tested out at https://personalcancertoolkit.org

with username:password - demo1:Admin123
