### ISSUE TITLE
When adding a connection, patient can include a note to include in invitation

### ISSUE THREAD

**Issue by bmamlin** [maurya/openmrs-module-patientportaltoolkit#119]

**Comment by maurya** [comment]
<img width="1163" alt="screen shot 2017-02-14 at 5 13 28 pm" src="https://cloud.githubusercontent.com/assets/1560244/22951912/025d0db6-f2d9-11e6-9970-2719ac693f74.png">

**Comment by maurya** [comment]
Add the note above Accept request

**Comment by maurya** [comment]
https://github.com/maurya/openmrs-module-patientportaltoolkit/commit/9d8641debd87cf7f16cb3b0e928ddac9cddfb79e
<img width="1188" alt="screen shot 2017-02-22 at 1 32 00 pm" src="https://cloud.githubusercontent.com/assets/1560244/23226414/74bb6990-f903-11e6-9d12-f06260a92cc7.png">
