### ISSUE TITLE
Create custom error page

### ISSUE THREAD

**Issue by bmamlin** [maurya/openmrs-module-patientportaltoolkit#126]
We should not show stacktraces to users; rather, the system should have a custom error page that explains a problem has occurred and provides a link to the home page.

A pretty error page for _any_ error in the application should present a branded "Oops. Something went wrong." with a link directing them back to the home page.

Ideally, when an exception occurs, we should log not only the stacktrace but as much context as possible to help us understand or recreate the error (e.g., current user, source URL, ...)

**Comment by maurya** [comment]
<img width="1616" alt="screen shot 2017-05-04 at 12 42 44 pm" src="https://cloud.githubusercontent.com/assets/1560244/25714817/4b0534ae-30c7-11e7-9431-a4aeb84bdef8.png">
