### ISSUE TITLE
Add sorting options to CancerBuddies

### ISSUE THREAD

**Issue by bmamlin** [maurya/openmrs-module-patientportaltoolkit#129]
We would like to be able to sort or group the list of patients in CancerBuddies by age, gender.

Consider grouping people similar in age up front by default.

**Comment by uladkasach** [comment]
I've issued a pull request with the requested functionality: https://github.com/maurya/openmrs-module-patientportaltoolkit/pull/134

Summary of changes:
1) Sorting can now be done on any desired attributes with orderings of asc, desc, closest, furthest
2) Buddies sorted by closest age on page load
3) UI for sorting added for users
4) CancerBuddies Thumbnails templated for readability and maintainability

![image](https://cloud.githubusercontent.com/assets/10381896/23673715/5017e0e4-0341-11e7-87e0-29cbab740faf.png)

**Comment by maurya** [comment]
Verified and Merged
