### ISSUE TITLE
Show upcoming reminders and Mark Completed action on Preventive Care screen (above calendar)

### ISSUE THREAD

**Issue by bmamlin** [maurya/openmrs-module-patientportaltoolkit#130]
Add list above calendar on Preventive Care screen similar to how this is done on Follow Up Care screen (above calendar).

**Comment by maurya** [comment]
<img width="1232" alt="screen shot 2017-02-22 at 3 51 22 pm" src="https://cloud.githubusercontent.com/assets/1560244/23231712/d0b634d8-f916-11e6-9464-efbf400451d7.png">
