### ISSUE TITLE
Add ability to click on an entry in the calendar to mark it completed.

### ISSUE THREAD

**Issue by bmamlin** [maurya/openmrs-module-patientportaltoolkit#131]
In both Preventive Care and Follow Up Care calendars, allow user to click on old entries to mark them as completed (and filling out any associated form).

**Comment by uladkasach** [comment]
Completed with pull request #173 

Upon clicking on a calendar date with events associated with it, creates a persistent 'popover' - upon which clickable titles of events are presented. Clicking on a name brings up its related markcompleted/manage modal.

![screenshot_2017-04-20_16-31-36](https://cloud.githubusercontent.com/assets/10381896/25251438/5b3b628e-25e7-11e7-9f1a-b06b5d35c13e.png)
