### ISSUE TITLE
Moving Symptom Management to Main Server

### ISSUE THREAD

**Issue by maurya** [maurya/openmrs-module-patientportaltoolkit#142]

**Comment by uladkasach** [comment]
Waiting on /js/ and /css/ files from Skip.

**Comment by uladkasach** [comment]
Symptom Management standalone app can be found hosted at `http://138.197.69.84`. Waiting to move it onto server.

**Comment by uladkasach** [comment]
Symptom Managment has been migrated to the demo server successfully. http://personalcancertoolkit.org/symptom-managment/

**Comment by maurya** [comment]
<img width="1461" alt="screen shot 2017-04-06 at 4 24 05 pm" src="https://cloud.githubusercontent.com/assets/1560244/24774056/7ef3a5a4-1ae5-11e7-9e19-6bf7b28fa948.png">
