### ISSUE TITLE
Preventive care reminders should implement the logic to check if there are completed preventive cares

### ISSUE THREAD

**Issue by maurya** [maurya/openmrs-module-patientportaltoolkit#144]
<img width="1330" alt="screen shot 2017-03-17 at 4 24 25 pm" src="https://cloud.githubusercontent.com/assets/1560244/24061549/36f2591a-0b2e-11e7-9d91-692c148c9567.png">

**Comment by uladkasach** [comment]
This has been completed with commit https://github.com/maurya/openmrs-module-patientportaltoolkit/pull/198/commits/cd622d81a49a0684985481b5b01eaf5d78cb0951, of pull request https://github.com/maurya/openmrs-module-patientportaltoolkit/pull/198. 

This implementation requires an SQL update, which can be found in `/0_meta/sql/`.

Note, in this implementation I've made the assumption that only one question (concept) associated with each `preventiveCareEvent` form will ask for a `datetime` datatype as a response and that this response is the completed date. From the events that i've been able to test, that has been the case. If that ever becomes not the case, we will have to specify exactly which concepts in the forms do correspond to the completed date.  

![screenshot_2017-05-09_16-20-56](https://cloud.githubusercontent.com/assets/10381896/25870846/99e8eac4-34d3-11e7-9a9b-7ea51ed5f0d4.png)
