### ISSUE TITLE
Upgrade Demo website to 2.5

### ISSUE THREAD

**Issue by maurya** [maurya/openmrs-module-patientportaltoolkit#146]

**Comment by maurya** [comment]
<img width="1341" alt="screen shot 2017-04-07 at 3 18 53 pm" src="https://cloud.githubusercontent.com/assets/1560244/24816105/8cbfb07c-1ba5-11e7-9057-c2bbe780340b.png">


This is mostly done there are some nginx config conflicts with Symptom Management config
@uladkasach  is working on this

**Comment by uladkasach** [comment]
@maurya done.
