### ISSUE TITLE
Create a GoogleMaps API key

### ISSUE THREAD

**Issue by maurya** [maurya/openmrs-module-patientportaltoolkit#162]
this is needed for getting Community map working in the demo environment

**Comment by uladkasach** [comment]
https://developers.google.com/maps/documentation/javascript/get-api-key

**Comment by maurya** [comment]
<img width="1258" alt="screen shot 2017-04-13 at 5 06 49 pm" src="https://cloud.githubusercontent.com/assets/1560244/25024367/aba92c0a-206b-11e7-9f24-ac26180549d8.png">
Setup in the demo server
