### ISSUE TITLE
Four patterns of symptom history

### ISSUE THREAD

**Issue by uladkasach** [maurya/openmrs-module-patientportaltoolkit#209]
Flat
Rising
Decreasing
Spike

2 week long interval

**Comment by maurya** [comment]
Added to the patient user for the first four graphs

**Comment by maurya** [comment]
<img width="1405" alt="screen shot 2017-05-12 at 1 40 23 pm" src="https://cloud.githubusercontent.com/assets/1560244/26009850/9bafc7be-3718-11e7-9cff-57b0e09fe2ad.png">
<img width="992" alt="screen shot 2017-05-12 at 1 40 29 pm" src="https://cloud.githubusercontent.com/assets/1560244/26009851/9d2c1b06-3718-11e7-8401-f77aebdb2fac.png">
