### ISSUE TITLE
Elements in the Treatments page are not aligned

### ISSUE THREAD

**Issue by maurya** [maurya/openmrs-module-patientportaltoolkit#4]
The field names and field inputs should be left and right aligned

**Comment by uladkasach** [comment]
Completed with pull request https://github.com/maurya/openmrs-module-patientportaltoolkit/pull/201

![image](https://cloud.githubusercontent.com/assets/10381896/25909290/bf0fa34a-357a-11e7-9c56-987fed0dfaa3.png)
