### ISSUE TITLE
Join/Unjoin Community Action

### ISSUE THREAD

**Issue by maurya** [maurya/openmrs-module-patientportaltoolkit#51]
[Done]1) Add the option in DB to store this value
2) Create a Description option that displays on the Jumbotron
3) Create a switch option (probably on the Jumbotron) that allows the user to enable or disable the join community option
[done]4) should be able to interact(messages) with people in the community without adding a relationship

**Comment by okspry** [comment]
I can add a new ticket, if you prefer, but here's a page for viewing the visible users.

http://codepen.io/okspry/pen/53278d3451a84f3923d1afabae8b1a6b/?editors=1000

**Comment by maurya** [comment]
Need to work in 2 and 4

**Comment by okspry** [comment]
Hope things are going well!

**Comment by maurya** [comment]
@okspry , Haha, hopefully Yes

**Comment by maurya** [comment]
<img width="1382" alt="screen shot 2017-04-13 at 4 31 16 pm" src="https://cloud.githubusercontent.com/assets/1560244/25023182/dafe3d92-2066-11e7-9610-37d0fa398b5d.png">
